# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    lane :generate_screenshots do
        gradle(
            task: 'Assemble',
            build_type: 'Debug',
        )

        gradle(
            task: ':app:AssembleAndroidTest',
        )

        screengrab()
    end
end
